name: TL2-Mikuro-Console-Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Build Solution
      run: |
        msbuild.exe TL2-Mikuro-Console.csproj -t:rebuild -verbosity:diag -property:Configuration=Release
               
